title: nikescar.github.io
description: personal page.
show_downloads: false
# remote_theme: nikescar/jekyll-theme-rtd
remote_theme : https://github.com/nikescar/jekyll-theme-rtd
plugins:
- jekyll-remote-theme

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
repo_url: 'https://nikescar.github.io'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
# prev_next_buttons_location: both
search_enabled: false
site_author: Woojae, Park
# logo: 'https://tui.dure.app/assets/css/theme.css'
site_favicon: 'assets/img/favicon.ico'
# prev_next_buttons_location: None
# prev_next_buttons_location: top
# prev_next_buttons_location: bottom
prev_next_buttons_location: both
# google_analytics: UA-XXXXX-Y
google_analytics_anonymize_ip: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist
exclude: []
